## NumPy practice round 2

In [4]:
import numpy as np

In [6]:
a1 = np.array([1,2,3])

In [7]:
a1

array([1, 2, 3])

In [13]:
a2 = np.array([[1,2,3],
             [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a2.shape

(2, 3)

In [32]:
a3 = np.array([[[1,2,3],
               [4,5,6],
              [7,8,9]],
              [[10,11,12],
               [13,14,15],
               [16,17,18]]])

a4 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [33]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [34]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [36]:
a1.shape, a1.dtype, a1.ndim, a1.size

((3,), dtype('int64'), 1, 3)

In [37]:
a2.shape, a2.dtype, a2.ndim,a2.size

((2, 3), dtype('int64'), 2, 6)

In [38]:
a3.shape, a3.dtype, a3.ndim, a3.size

((2, 3, 3), dtype('int64'), 3, 18)

In [39]:
import pandas as pd

In [41]:
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [42]:
ones = np.ones(shape =(10,2))

In [43]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [44]:
zeros = np.zeros(shape=(7,2,3))

In [45]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [47]:
by_3s = np.arange(0,100,3)
by_3s

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [48]:
random_1 = np.random.randint(0,10,size=(7,2))
random_1

array([[5, 7],
       [8, 8],
       [9, 2],
       [7, 5],
       [8, 3],
       [1, 8],
       [6, 1]])

In [54]:
random_2 = np.random.random((3,5))

In [55]:
random_2

array([[0.05675975, 0.70054609, 0.84455361, 0.6909876 , 0.80707924],
       [0.76937287, 0.36594826, 0.87483777, 0.49154581, 0.55839859],
       [0.77615915, 0.23295042, 0.54964808, 0.87058127, 0.09415388]])

In [59]:
np.random.seed(seed=42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
random_3 = np.random.randint(0,10,size=(4,6))
random_3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [64]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_4 = np.random.randint(1,10,size=(3,7))
random_4



array([[9, 7, 9, 8, 2, 1, 7],
       [7, 8, 5, 3, 8, 6, 3],
       [1, 3, 5, 3, 1, 5, 7]])

In [65]:
random_4[0]

array([9, 7, 9, 8, 2, 1, 7])

In [69]:
# Get the first 2 rows of latest array you created
random_4[:2]

array([[9, 7, 9, 8, 2, 1, 7],
       [7, 8, 5, 3, 8, 6, 3]])

In [74]:
# Get the first 2 values of the first 2 rows of the latest array
random_4[0:2,0:2]

array([[9, 7],
       [7, 8]])

In [77]:
random_4[0:3,0:5]

array([[9, 7, 9, 8, 2],
       [7, 8, 5, 3, 8],
       [1, 3, 5, 3, 1]])

In [83]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
math_1 = np.random.randint(0,10,size=(3,5))
math_2 = np.ones(shape=(3,5))
math_1,math_2

(array([[1, 5, 6, 4, 0],
        [0, 2, 1, 4, 9],
        [5, 6, 3, 6, 7]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [84]:
math_1 + math_2

array([[ 2.,  6.,  7.,  5.,  1.],
       [ 1.,  3.,  2.,  5., 10.],
       [ 6.,  7.,  4.,  7.,  8.]])

In [86]:
# Create another array of ones of shape (5, 3)
math_3 = np.ones(shape=(5,3))

In [87]:
math_1 + math_3

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [88]:
math_1 + math_3.T

array([[ 2.,  6.,  7.,  5.,  1.],
       [ 1.,  3.,  2.,  5., 10.],
       [ 6.,  7.,  4.,  7.,  8.]])

In [89]:
# Create another array of ones of shape (3, 5)
again_1 = np.ones(shape=(3,5))

In [92]:
# Subtract the new array of ones from the other most recent array
math_1-again_1

array([[ 0.,  4.,  5.,  3., -1.],
       [-1.,  1.,  0.,  3.,  8.],
       [ 4.,  5.,  2.,  5.,  6.]])

In [93]:
# Multiply the ones array with the latest array
math_1 * again_1

array([[1., 5., 6., 4., 0.],
       [0., 2., 1., 4., 9.],
       [5., 6., 3., 6., 7.]])

In [94]:
# Take the latest array to the power of 2 using '**'
again_1**2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [95]:
# Do the same thing with np.square()
np.square(math_1)

array([[ 1, 25, 36, 16,  0],
       [ 0,  4,  1, 16, 81],
       [25, 36,  9, 36, 49]])

In [96]:
# Find the mean of the latest array using np.mean()
np.mean(math_1)

3.933333333333333

In [97]:
# Find the maximum of the latest array using np.max()
np.max(math_1)

9

In [98]:
# Find the minimum of the latest array using np.min()
np.min(math_1)

0

In [99]:
# Find the standard deviation of the latest array
math_1.std

<function ndarray.std>

In [100]:
np.std(math_1)

2.619584360585133

In [101]:
# Find the variance of the latest array
np.var(math_1)

6.862222222222221

In [103]:
# Reshape the latest array to (3, 5, 1)
math_2.reshape(3,5,1)

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [104]:
math_2.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [105]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
more_1 = np.random.randint(0,10,size=(3,3))
more_2 = np.random.randint(0,10,size=(3,2))
more_1, more_2

(array([[0, 5, 7],
        [4, 3, 1],
        [5, 5, 0]]),
 array([[8, 5],
        [2, 3],
        [3, 2]]))

In [106]:
# Perform a dot product on the two newest arrays you created
more_1.dot(more_2)

array([[31, 29],
       [41, 31],
       [50, 40]])

In [107]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
ahhh_1 = np.random.randint(0,10,size=(4,3))
ahhh_2 = np.random.randint(0,10,size=(4,3))

In [110]:
ahhh_1.dot(ahhh_2.T)

array([[32, 39, 48, 78],
       [72, 66, 69, 42],
       [56, 71, 79, 64],
       [64, 75, 81, 51]])

In [111]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
even_more_1 = np.random.randint(0,10,size=(3,5,6))
even_more_2 =np.random.randint(0,10,size=(3,5,6))

In [112]:
even_more_1

array([[[1, 0, 4, 4, 6, 8],
        [8, 2, 2, 2, 3, 7],
        [5, 7, 0, 7, 3, 0],
        [7, 3, 5, 7, 3, 2],
        [8, 2, 8, 1, 1, 1]],

       [[5, 2, 8, 3, 0, 3],
        [0, 4, 3, 7, 7, 6],
        [2, 0, 0, 2, 5, 6],
        [5, 5, 5, 2, 5, 7],
        [1, 4, 0, 0, 4, 2]],

       [[3, 2, 0, 0, 4, 5],
        [2, 8, 4, 7, 0, 4],
        [2, 0, 3, 4, 6, 0],
        [2, 1, 8, 9, 5, 9],
        [2, 7, 7, 1, 5, 6]]])

In [113]:
# Compare the two arrays with '>'
even_more_1 > even_more_2

array([[[False, False,  True, False,  True,  True],
        [ True, False, False, False, False,  True],
        [False,  True, False, False, False, False],
        [ True, False,  True,  True,  True, False],
        [ True, False,  True, False, False, False]],

       [[ True, False, False, False, False, False],
        [False,  True, False, False,  True,  True],
        [False, False, False, False,  True, False],
        [ True, False,  True, False, False, False],
        [False,  True, False, False,  True, False]],

       [[ True, False, False, False, False, False],
        [False,  True, False,  True, False, False],
        [False, False,  True, False, False, False],
        [False,  True,  True,  True, False,  True],
        [False, False,  True, False, False, False]]])

In [114]:
# Compare the two arrays with '>='
even_more_1 >= even_more_2

array([[[ True, False,  True, False,  True,  True],
        [ True, False, False, False, False,  True],
        [False,  True, False, False, False, False],
        [ True, False,  True,  True,  True, False],
        [ True, False,  True,  True, False, False]],

       [[ True, False, False, False, False, False],
        [False,  True,  True, False,  True,  True],
        [False,  True, False, False,  True,  True],
        [ True,  True,  True,  True, False,  True],
        [False,  True, False, False,  True, False]],

       [[ True, False, False, False,  True, False],
        [False,  True, False,  True,  True, False],
        [False,  True,  True, False, False, False],
        [False,  True,  True,  True,  True,  True],
        [ True, False,  True, False,  True, False]]])

In [115]:
# Find which elements of the first array are greater than 7
even_more_1 >7

array([[[False, False, False, False, False,  True],
        [ True, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [ True, False,  True, False, False, False]],

       [[False, False,  True, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False]],

       [[False, False, False, False, False, False],
        [False,  True, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False,  True,  True, False,  True],
        [False, False, False, False, False, False]]])

In [116]:
# Which parts of each array are equal? (try using '==')
even_more_1 == even_more_2

array([[[ True, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False,  True, False, False]],

       [[False, False, False, False, False, False],
        [False, False,  True, False, False, False],
        [False,  True, False, False, False,  True],
        [False,  True, False,  True, False,  True],
        [False, False, False, False, False, False]],

       [[False, False, False, False,  True, False],
        [False, False, False, False,  True, False],
        [False,  True, False, False, False, False],
        [False, False, False, False,  True, False],
        [ True, False, False, False,  True, False]]])

In [118]:
# Sort one of the arrays you just created in ascending order
np.sort(even_more_1)

array([[[0, 1, 4, 4, 6, 8],
        [2, 2, 2, 3, 7, 8],
        [0, 0, 3, 5, 7, 7],
        [2, 3, 3, 5, 7, 7],
        [1, 1, 1, 2, 8, 8]],

       [[0, 2, 3, 3, 5, 8],
        [0, 3, 4, 6, 7, 7],
        [0, 0, 2, 2, 5, 6],
        [2, 5, 5, 5, 5, 7],
        [0, 0, 1, 2, 4, 4]],

       [[0, 0, 2, 3, 4, 5],
        [0, 2, 4, 4, 7, 8],
        [0, 0, 2, 3, 4, 6],
        [1, 2, 5, 8, 9, 9],
        [1, 2, 5, 6, 7, 7]]])

In [119]:
# Sort the indexes of one of the arrays you just created
np.argsort(even_more_1)

array([[[1, 0, 2, 3, 4, 5],
        [1, 2, 3, 4, 5, 0],
        [2, 5, 4, 0, 1, 3],
        [5, 1, 4, 2, 0, 3],
        [3, 4, 5, 1, 0, 2]],

       [[4, 1, 3, 5, 0, 2],
        [0, 2, 1, 5, 3, 4],
        [1, 2, 0, 3, 4, 5],
        [3, 0, 1, 2, 4, 5],
        [2, 3, 0, 5, 1, 4]],

       [[2, 3, 1, 0, 4, 5],
        [4, 0, 2, 5, 3, 1],
        [1, 5, 0, 2, 3, 4],
        [1, 0, 4, 2, 3, 5],
        [3, 0, 4, 5, 1, 2]]])

In [120]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(even_more_1)

81

In [122]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(even_more_1)

1

In [123]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(even_more_1,axis=1)

array([[1, 2, 4, 2, 0, 0],
       [0, 3, 0, 1, 1, 3],
       [0, 1, 3, 3, 2, 3]])

In [124]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(even_more_1,axis=0)

array([[0, 0, 2, 2, 1, 1],
       [1, 0, 0, 0, 2, 2],
       [1, 1, 0, 1, 0, 0],
       [2, 2, 0, 1, 0, 0],
       [1, 0, 1, 1, 0, 0]])

In [127]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[-0.68000433, -0.26340584, -0.28065488, -0.60397592, -0.54925291],
       [ 1.09679625,  2.11311216, -0.49840662, -0.32439545,  0.524609  ],
       [ 3.18703334,  0.08416352,  0.97263287,  1.54447484,  0.34406813]])

In [126]:
# Create an array with 10 evenly spaced numbers between 1 and 100
by_10s = np.
by_10s

/var/folders/2k/jf917mwj5qn53k_ygc5zs9h40000gn/T/ipykernel_99991/1200270474.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  by_10s = np.int(1,100,10)


TypeError: int() takes at most 2 arguments (3 given)

In [128]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])